/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.electrosaur.trapper;

import org.junit.Test;
import java.io.File;
import java.io.IOException;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testCreateMultiLayerPSD() throws IOException {
        String testFilename = "test-output.psd";
        App.createMultiLayerPSD(testFilename);

        File testFile = new File(testFilename);
        assertTrue("PSD file should be created", testFile.exists());
        assertTrue("PSD file should have content", testFile.length() > 0);

        // Clean up test file
        testFile.delete();
    }
}
