/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.electrosaur.trapper;

import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.*;
import java.nio.ByteBuffer;
import java.nio.channels.FileChannel;

public class App {

    public static void main(String[] args) {
        try {
            createMultiLayerPSD("output.psd");
            System.out.println("Multi-layer PSD file created successfully: output.psd");
        } catch (IOException e) {
            System.err.println("Error creating PSD file: " + e.getMessage());
            e.printStackTrace();
        }
    }

    /**
     * Creates a multi-layer Photoshop PSD file with two layers:
     * - Lower layer: white 200x200 square
     * - Upper layer: black 100x100 square (centered on the same point)
     * Both on a 200x200 pixel canvas
     */
    public static void createMultiLayerPSD(String filename) throws IOException {
        int canvasSize = 200;
        int lowerLayerSize = 200;
        int upperLayerSize = 100;

        // Create lower layer: white square (200x200)
        BufferedImage lowerLayer = new BufferedImage(lowerLayerSize, lowerLayerSize, BufferedImage.TYPE_INT_RGB);
        Graphics2D g1 = lowerLayer.createGraphics();
        g1.setColor(Color.WHITE);
        g1.fillRect(0, 0, lowerLayerSize, lowerLayerSize);
        g1.dispose();

        // Create upper layer: black square (100x100) with transparent background
        BufferedImage upperLayer = new BufferedImage(upperLayerSize, upperLayerSize, BufferedImage.TYPE_INT_ARGB);
        Graphics2D g2 = upperLayer.createGraphics();
        // Start with fully transparent background
        g2.setComposite(java.awt.AlphaComposite.Clear);
        g2.fillRect(0, 0, upperLayerSize, upperLayerSize);
        // Draw black square
        g2.setComposite(java.awt.AlphaComposite.Src);
        g2.setColor(Color.BLACK);
        g2.fillRect(0, 0, upperLayerSize, upperLayerSize);
        g2.dispose();

        try (RandomAccessFile raf = new RandomAccessFile(filename, "rw");
             FileChannel channel = raf.getChannel()) {

            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            DataOutputStream dos = new DataOutputStream(baos);

            // File Header (26 bytes)
            dos.writeBytes("8BPS");           // Signature
            dos.writeShort(1);                // Version
            dos.write(new byte[6]);           // Reserved
            dos.writeShort(3);                // Channels (RGB)
            dos.writeInt(canvasSize);         // Height
            dos.writeInt(canvasSize);         // Width
            dos.writeShort(8);                // Bits per channel
            dos.writeShort(3);                // Color mode (RGB)

            // Color Mode Data Section
            dos.writeInt(0);                  // No color mode data

            // Image Resources Section
            dos.writeInt(0);                  // No image resources

            // Layer and Mask Information Section
            ByteArrayOutputStream layerInfoStream = new ByteArrayOutputStream();
            DataOutputStream layerInfo = new DataOutputStream(layerInfoStream);

            // Layer info
            layerInfo.writeShort(2);          // Number of layers

            // Layer 1 (lower layer - white, 200x200, positioned at origin)
            writeLayerRecord(layerInfo, 0, 0, lowerLayerSize, lowerLayerSize, "Lower Layer", lowerLayer, false);

            // Layer 2 (upper layer - black, 100x100, centered on canvas, with transparency)
            int upperLayerOffset = (canvasSize - upperLayerSize) / 2;
            writeLayerRecord(layerInfo, upperLayerOffset, upperLayerOffset, upperLayerSize, upperLayerSize, "Upper Layer", upperLayer, true);

            // Write layer image data
            writeLayerImageData(layerInfo, lowerLayer, false);
            writeLayerImageData(layerInfo, upperLayer, true);

            byte[] layerInfoBytes = layerInfoStream.toByteArray();
            dos.writeInt(layerInfoBytes.length + 4);  // Layer and mask section length
            dos.writeInt(layerInfoBytes.length);      // Layer info length
            dos.write(layerInfoBytes);

            // Image Data Section (merged/flattened composite image)
            // Create composite image showing both layers
            BufferedImage composite = new BufferedImage(canvasSize, canvasSize, BufferedImage.TYPE_INT_RGB);
            Graphics2D gc = composite.createGraphics();
            // Draw lower layer (white square fills entire canvas)
            gc.drawImage(lowerLayer, 0, 0, null);
            // Draw upper layer (black square centered)
            gc.drawImage(upperLayer, upperLayerOffset, upperLayerOffset, null);
            gc.dispose();

            dos.writeShort(0);  // Compression: Raw
            writeImageData(dos, composite);

            // Write to file
            channel.write(ByteBuffer.wrap(baos.toByteArray()));
        }
    }

    private static void writeLayerRecord(DataOutputStream dos, int left, int top, int width, int height, String name, BufferedImage img, boolean hasAlpha) throws IOException {
        dos.writeInt(top);              // Top
        dos.writeInt(left);             // Left
        dos.writeInt(top + height);     // Bottom
        dos.writeInt(left + width);     // Right

        int numChannels = hasAlpha ? 4 : 3;
        dos.writeShort(numChannels);    // Number of channels (RGBA or RGB)

        // Channel info
        if (hasAlpha) {
            dos.writeShort(-1);         // Channel ID -1 = transparency mask (alpha)
            dos.writeInt(width * height + 2);  // Data length (+ 2 for compression)
        }
        for (int i = 0; i < 3; i++) {
            dos.writeShort(i);          // Channel ID (0=R, 1=G, 2=B)
            dos.writeInt(width * height + 2);  // Data length (+ 2 for compression)
        }

        dos.writeBytes("8BIM");    // Blend mode signature
        dos.writeBytes("norm");    // Blend mode key (normal)
        dos.writeByte(255);        // Opacity
        dos.writeByte(0);          // Clipping
        dos.writeByte(0);          // Flags
        dos.writeByte(0);          // Filler

        // Extra data
        ByteArrayOutputStream extraData = new ByteArrayOutputStream();
        DataOutputStream extra = new DataOutputStream(extraData);

        // Layer mask data
        extra.writeInt(0);

        // Layer blending ranges
        extra.writeInt(0);

        // Layer name (Pascal string)
        byte[] nameBytes = name.getBytes("ISO-8859-1");
        extra.writeByte(Math.min(nameBytes.length, 255));
        extra.write(nameBytes);
        // Pad to multiple of 4
        int padding = (4 - ((nameBytes.length + 1) % 4)) % 4;
        extra.write(new byte[padding]);

        byte[] extraBytes = extraData.toByteArray();
        dos.writeInt(extraBytes.length);
        dos.write(extraBytes);
    }

    private static void writeLayerImageData(DataOutputStream dos, BufferedImage img, boolean hasAlpha) throws IOException {
        int width = img.getWidth();
        int height = img.getHeight();

        // Write alpha channel first if present (channel ID -1)
        if (hasAlpha) {
            dos.writeShort(0);  // No compression
            for (int y = 0; y < height; y++) {
                for (int x = 0; x < width; x++) {
                    int argb = img.getRGB(x, y);
                    int alpha = (argb >> 24) & 0xFF;  // Alpha channel
                    dos.writeByte(alpha);
                }
            }
        }

        // Write each channel (R, G, B)
        for (int channel = 0; channel < 3; channel++) {
            dos.writeShort(0);  // No compression
            for (int y = 0; y < height; y++) {
                for (int x = 0; x < width; x++) {
                    int rgb = img.getRGB(x, y);
                    int value;
                    if (channel == 0) value = (rgb >> 16) & 0xFF;  // Red
                    else if (channel == 1) value = (rgb >> 8) & 0xFF;   // Green
                    else value = rgb & 0xFF;                            // Blue
                    dos.writeByte(value);
                }
            }
        }
    }

    private static void writeImageData(DataOutputStream dos, BufferedImage img) throws IOException {
        int width = img.getWidth();
        int height = img.getHeight();

        // Write interleaved RGB data
        for (int channel = 0; channel < 3; channel++) {
            for (int y = 0; y < height; y++) {
                for (int x = 0; x < width; x++) {
                    int rgb = img.getRGB(x, y);
                    int value;
                    if (channel == 0) value = (rgb >> 16) & 0xFF;  // Red
                    else if (channel == 1) value = (rgb >> 8) & 0xFF;   // Green
                    else value = rgb & 0xFF;                            // Blue
                    dos.writeByte(value);
                }
            }
        }
    }
}
